apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker1
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.4
        args: ["start-dev"] # Geliştirme modu: Ayarları web arayüzünden elinle yapabilmen için
        env:
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL
          valueFrom: { configMapKeyRef: { name: bank-config, key: KC_DB_URL } }
        - name: KC_DB_USERNAME
          valueFrom: { secretKeyRef: { name: bank-secrets, key: KC_DB_USER } }
        - name: KC_DB_PASSWORD
          valueFrom: { secretKeyRef: { name: bank-secrets, key: KC_DB_PASS } }
        - name: KEYCLOAK_ADMIN
          valueFrom: { secretKeyRef: { name: bank-secrets, key: KC_ADMIN_USER } }
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom: { secretKeyRef: { name: bank-secrets, key: KC_ADMIN_PASS } }
        # 🚀 AŞAĞIDAKİ İKİ YENİ SİBER KALKANI EKLİYORUZ
        - name: KC_PROXY_HEADERS
          value: "xforwarded"
        - name: KC_HOSTNAME
          value: "auth.bank.local"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080